CREATE TABLE SYS_SEQUENCE (
   NAME varchar(50) NOT NULL,
   CURRENT_VALUE int(11) NOT NULL DEFAULT '0',
   INCREMENT int(11) NOT NULL DEFAULT '1',
   PRIMARY KEY (NAME)
 );
 
 INSERT INTO SYS_SEQUENCE(NAME,CURRENT_VALUE,INCREMENT) VALUES('sequenceName', 1,1);
 INSERT INTO SYS_SEQUENCE(NAME,CURRENT_VALUE,INCREMENT) VALUES('SEQ_USER_CZ_LOG', 1,1);
 INSERT INTO SYS_SEQUENCE(NAME,CURRENT_VALUE,INCREMENT) VALUES('SEQ_FR_SERVICE_STATISTICS', 1,1);
 INSERT INTO SYS_SEQUENCE(NAME,CURRENT_VALUE,INCREMENT) VALUES('SEQ_FR_SQL_STATISTICS', 1,1);
 INSERT INTO SYS_SEQUENCE(NAME,CURRENT_VALUE,INCREMENT) VALUES('SEQ_EXCEPTION_LOG', 1,1);
 INSERT INTO SYS_SEQUENCE(NAME,CURRENT_VALUE,INCREMENT) VALUES('SEQ_BUSINESS_TJ_LOG', 1,1);
 INSERT INTO SYS_SEQUENCE(NAME,CURRENT_VALUE,INCREMENT) VALUES('SEQ_FR_SQL_MESSAGE_COMMON', 1,1);
 INSERT INTO SYS_SEQUENCE(NAME,CURRENT_VALUE,INCREMENT) VALUES('SEQ_FR_ACTION_STATISTICS', 1,1);
 INSERT INTO SYS_SEQUENCE(NAME,CURRENT_VALUE,INCREMENT) VALUES('SEQ_QX_GNMK_TREE_JD_DM', 10000000,1);
 
 
 commit;
 
 
 
 DELIMITER $$

DROP FUNCTION IF EXISTS `currval`$$

CREATE DEFINER=`root`@`%` FUNCTION `currval`(seq_name VARCHAR(50)) RETURNS INT(11)
BEGIN
DECLARE VALUE INTEGER;
SET VALUE=0;
SELECT current_value INTO VALUE
FROM sys_sequence 
WHERE NAME=seq_name;
RETURN VALUE;
END$$

DELIMITER ;


DELIMITER $$
DROP FUNCTION IF EXISTS `nextval`$$

CREATE DEFINER=`root`@`%` FUNCTION `nextval`(seq_name varchar(50)) RETURNS int(11)
BEGIN
UPDATE sys_sequence
SET CURRENT_VALUE = CURRENT_VALUE + INCREMENT
where name=seq_name;
return currval(seq_name);
END$$

DELIMITER $$  
DROP FUNCTION IF EXISTS F_FRAME_SEQUENCE $$  
CREATE FUNCTION F_FRAME_SEQUENCE (sequenceName varchar(50)) RETURNS varchar(20)  
BEGIN  
DECLARE sequenceNo varchar(20) DEFAULT '';
DECLARE prefix varchar(4) DEFAULT '9';
    select nextval(sequenceName) into sequenceNo;
    SET sequenceNo = lpad(sequenceNo,8,'0');
    SET sequenceNo = CONCAT(prefix,date_format(NOW(),'%Y%m%d'),'9',sequenceNo,'00');
RETURN sequenceNo;  
END $$  
DELIMITER ;
