-- 创建表: 消息字段定义
create table MESSAGE_FIELD_DEFINITION
(
  NAME         VARCHAR(128) not null comment '消息字段名称',
  IS_CUSTOM    CHAR(1) not null comment '是否为自定义字段',
  CONTENT_TYPE CHAR(2) comment '字段内容类型（暂不支持，留空）',
  DESCRIPTION  VARCHAR(256) comment '字段说明'
) comment '消息字段定义'
;

alter table MESSAGE_FIELD_DEFINITION
  add constraint PK_MESSAGE_FIELD_DEF primary key (NAME);

insert into MESSAGE_FIELD_DEFINITION (NAME, IS_CUSTOM, CONTENT_TYPE, DESCRIPTION)
values ('ALLOWDELETE', 'N', '', '是否允许删除');

insert into MESSAGE_FIELD_DEFINITION (NAME, IS_CUSTOM, CONTENT_TYPE, DESCRIPTION)
values ('ARCHIVETIME', 'N', '', '归档时间');

insert into MESSAGE_FIELD_DEFINITION (NAME, IS_CUSTOM, CONTENT_TYPE, DESCRIPTION)
values ('AVAILABLEUNTIL', 'N', '', '有效期/办结期限');

insert into MESSAGE_FIELD_DEFINITION (NAME, IS_CUSTOM, CONTENT_TYPE, DESCRIPTION)
values ('COMMENTS', 'N', '', '备注');

insert into MESSAGE_FIELD_DEFINITION (NAME, IS_CUSTOM, CONTENT_TYPE, DESCRIPTION)
values ('CREATEDBY', 'N', '', '创建人');

insert into MESSAGE_FIELD_DEFINITION (NAME, IS_CUSTOM, CONTENT_TYPE, DESCRIPTION)
values ('CREATEDBY_NAME', 'Y', '  ', '发送人');

insert into MESSAGE_FIELD_DEFINITION (NAME, IS_CUSTOM, CONTENT_TYPE, DESCRIPTION)
values ('CREATETIME', 'N', '', '创建时间');

insert into MESSAGE_FIELD_DEFINITION (NAME, IS_CUSTOM, CONTENT_TYPE, DESCRIPTION)
values ('FORMURL', 'Y', '  ', '任务表单');

insert into MESSAGE_FIELD_DEFINITION (NAME, IS_CUSTOM, CONTENT_TYPE, DESCRIPTION)
values ('ID', 'N', '', '消息编号');

insert into MESSAGE_FIELD_DEFINITION (NAME, IS_CUSTOM, CONTENT_TYPE, DESCRIPTION)
values ('INSTANCEID', 'Y', '  ', '流程实例ID');

insert into MESSAGE_FIELD_DEFINITION (NAME, IS_CUSTOM, CONTENT_TYPE, DESCRIPTION)
values ('ISARCHIVED', 'N', '', '是否归档');

insert into MESSAGE_FIELD_DEFINITION (NAME, IS_CUSTOM, CONTENT_TYPE, DESCRIPTION)
values ('LASTRECEIVEDBY', 'N', '', '最后接收人');

insert into MESSAGE_FIELD_DEFINITION (NAME, IS_CUSTOM, CONTENT_TYPE, DESCRIPTION)
values ('LASTRECEIVETIME', 'N', '', '最后接收时间');

insert into MESSAGE_FIELD_DEFINITION (NAME, IS_CUSTOM, CONTENT_TYPE, DESCRIPTION)
values ('MESSAGESYSTEMID', 'N', '', '来源消息系统号');

insert into MESSAGE_FIELD_DEFINITION (NAME, IS_CUSTOM, CONTENT_TYPE, DESCRIPTION)
values ('PRIORITY', 'N', '', '优先级');

insert into MESSAGE_FIELD_DEFINITION (NAME, IS_CUSTOM, CONTENT_TYPE, DESCRIPTION)
values ('STATUS', 'Y', '', '状态');

insert into MESSAGE_FIELD_DEFINITION (NAME, IS_CUSTOM, CONTENT_TYPE, DESCRIPTION)
values ('SYSTEMNAME', 'N', '', '系统名称');

insert into MESSAGE_FIELD_DEFINITION (NAME, IS_CUSTOM, CONTENT_TYPE, DESCRIPTION)
values ('TASKID', 'Y', '  ', '任务ID');

insert into MESSAGE_FIELD_DEFINITION (NAME, IS_CUSTOM, CONTENT_TYPE, DESCRIPTION)
values ('TOPIC', 'N', '', '主题');

insert into MESSAGE_FIELD_DEFINITION (NAME, IS_CUSTOM, CONTENT_TYPE, DESCRIPTION)
values ('TOPICURL', 'N', '', '主题链接url');

insert into MESSAGE_FIELD_DEFINITION (NAME, IS_CUSTOM, CONTENT_TYPE, DESCRIPTION)
values ('TYPE', 'N', '', '任务类型');

commit;